import type { Product, Coupon, User, Notification } from './types';

export const CATEGORIES: { id: string; label: string; emoji: string; color: string }[] = [
  { id: 'baby-diapers', label: 'Baby Diapers', emoji: '👶', color: 'from-sky-100 to-blue-100' },
  { id: 'adult-diapers', label: 'Adult Diapers', emoji: '🧓', color: 'from-violet-100 to-purple-100' },
  { id: 'sanitary-pads', label: 'Sanitary Pads', emoji: '🌸', color: 'from-pink-100 to-rose-100' },
  { id: 'panty-liners', label: 'Panty Liners', emoji: '🌷', color: 'from-fuchsia-100 to-pink-100' },
  { id: 'maternity-pads', label: 'Maternity Pads', emoji: '🤰', color: 'from-amber-100 to-orange-100' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Ultra Soft Baby Diapers',
    brand: 'Huggies',
    category: 'baby-diapers',
    price: 899,
    mrp: 1199,
    size: 'M (6-11 kg)',
    packOf: 60,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=500&auto=format&fit=crop',
    description: 'Cotton soft with 12-hour absorption, wetness indicator, and dermatologically tested.',
    rating: 4.6,
    absorbency: 'Heavy',
  },
  {
    id: 'p2',
    name: 'NewBorn Diapers Pants',
    brand: 'Pampers',
    category: 'baby-diapers',
    price: 499,
    mrp: 699,
    size: 'NB (0-5 kg)',
    packOf: 36,
    stock: 60,
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=500&auto=format&fit=crop',
    description: 'Specially designed for newborns with umbilical cord cutout and soft stretch.',
    rating: 4.8,
    absorbency: 'Regular',
  },
  {
    id: 'p3',
    name: 'Premium Baby Taped Diapers',
    brand: 'MamyPoko',
    category: 'baby-diapers',
    price: 1299,
    mrp: 1599,
    size: 'L (9-14 kg)',
    packOf: 72,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=500&auto=format&fit=crop',
    description: 'Extra absorb with slim-fit design and breathable soft material.',
    rating: 4.5,
    absorbency: 'Overnight',
  },
  {
    id: 'p4',
    name: 'Adult Pull-Up Diapers',
    brand: 'Depend',
    category: 'adult-diapers',
    price: 799,
    mrp: 999,
    size: 'M',
    packOf: 30,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=500&auto=format&fit=crop',
    description: 'Discreet and comfortable adult underwear with maximum absorbency.',
    rating: 4.4,
    absorbency: 'Heavy',
  },
  {
    id: 'p5',
    name: 'Adult Diaper Classic',
    brand: 'Friends',
    category: 'adult-diapers',
    price: 549,
    mrp: 749,
    size: 'L',
    packOf: 20,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=500&auto=format&fit=crop',
    description: 'Soft taped style with wetness indicator and anti-leak guards.',
    rating: 4.2,
    absorbency: 'Regular',
  },
  {
    id: 'p6',
    name: 'Ultra Thin Sanitary Pads',
    brand: 'Whisper',
    category: 'sanitary-pads',
    price: 349,
    mrp: 449,
    size: 'XL',
    packOf: 40,
    stock: 120,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&auto=format&fit=crop',
    description: 'Ultra thin with wings, odor lock, and 8-hour protection.',
    rating: 4.7,
    absorbency: 'Heavy',
  },
  {
    id: 'p7',
    name: 'Organic Cotton Sanitary Pads',
    brand: 'Nua',
    category: 'sanitary-pads',
    price: 399,
    mrp: 499,
    size: 'L',
    packOf: 12,
    stock: 80,
    image: 'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=500&auto=format&fit=crop',
    description: '100% organic cotton, rash-free, biodegradable top sheet.',
    rating: 4.6,
    absorbency: 'Regular',
  },
  {
    id: 'p8',
    name: 'Heavy Flow Night Pads',
    brand: 'Sofy',
    category: 'sanitary-pads',
    price: 299,
    mrp: 399,
    size: 'XXL',
    packOf: 20,
    stock: 95,
    image: 'https://images.unsplash.com/photo-1599733589096-6d0f0a5c1a49?w=500&auto=format&fit=crop',
    description: 'Extra long with 360° leak guard for overnight protection.',
    rating: 4.5,
    absorbency: 'Overnight',
  },
  {
    id: 'p9',
    name: 'Daily Fresh Panty Liners',
    brand: 'Carefree',
    category: 'panty-liners',
    price: 199,
    mrp: 249,
    packOf: 50,
    stock: 150,
    image: 'https://images.unsplash.com/photo-1587324456323-9a4d02c8f4c?w=500&auto=format&fit=crop',
    description: 'Ultra thin daily liners with fresh scent, soft cotton cover.',
    rating: 4.4,
    absorbency: 'Light',
  },
  {
    id: 'p10',
    name: 'Aloe Vera Panty Liners',
    brand: 'Sofy',
    category: 'panty-liners',
    price: 249,
    mrp: 329,
    packOf: 40,
    stock: 110,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop',
    description: 'Aloe vera infused for sensitive skin, pH balanced.',
    rating: 4.6,
    absorbency: 'Light',
  },
  {
    id: 'p11',
    name: 'Maternity Maxi Pads',
    brand: 'Stayfree',
    category: 'maternity-pads',
    price: 449,
    mrp: 599,
    packOf: 24,
    stock: 55,
    image: 'https://images.unsplash.com/photo-1609220136736-443140cffec6?w=500&auto=format&fit=crop',
    description: 'Extra long and super absorbent for post-partum bleeding.',
    rating: 4.7,
    absorbency: 'Heavy',
  },
  {
    id: 'p12',
    name: 'New Mom Maternity Kit',
    brand: 'R for Rabbit',
    category: 'maternity-pads',
    price: 699,
    mrp: 899,
    packOf: 30,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1544367527-de7a9a41b998?w=500&auto=format&fit=crop',
    description: 'Complete maternity kit with pads, mesh panties and breast pads.',
    rating: 4.8,
    absorbency: 'Overnight',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  { code: 'WELCOME10', discountPct: 10, maxDiscount: 100, minOrder: 299, active: true },
  { code: 'SAVE20', discountPct: 20, maxDiscount: 250, minOrder: 799, active: true },
  { code: 'FRESH5', discountPct: 5, maxDiscount: 50, minOrder: 199, active: true },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u1',
    name: 'Admin User',
    email: 'admin@softcare.in',
    phone: '9999999999',
    password: 'admin123',
    role: 'admin',
  },
  {
    id: 'u2',
    name: 'Rahul Kumar',
    email: 'rahul@example.com',
    phone: '9812345670',
    password: 'delivery123',
    role: 'delivery',
  },
  {
    id: 'u3',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '9876543210',
    password: 'customer123',
    role: 'customer',
    address: '123 Green Park, New Delhi - 110016',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    title: '🎉 Welcome Offer!',
    message: 'Use WELCOME10 to get 10% off on your first order.',
    type: 'offer',
    createdAt: Date.now() - 86400000,
    read: false,
  },
  {
    id: 'n2',
    title: '🚚 Free Delivery',
    message: 'On all orders above ₹499 for a limited time.',
    type: 'offer',
    createdAt: Date.now() - 172800000,
    read: true,
  },
];

export const STATUS_STEPS: string[] = ['Placed', 'Confirmed', 'Packed', 'Out for Delivery', 'Delivered'];
